global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "broker_api"
    static_configs:
      - targets: ["api-dev:8090"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgresql-exporter:9187"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
